[build]
  publish = "build"
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Place Netlify environment vars in [context.production.environment] if needed
